services:
  medisynchub.bootstrapper:
    image: ${DOCKER_REGISTRY-}medisynchubbootstrapper
    build:
      context: .
      dockerfile: MediSyncHub.API/MediSyncHub.Bootstrapper/Dockerfile
    container_name: medisync-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=MediSyncHub;Username=postgres;Password=techMenT0r@2024_2025
    ports:
      - "5000:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - medisync-network

  postgres:
    image: postgres:latest
    container_name: medisync-postgres
    environment:
      POSTGRES_DB: MediSyncHub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: techMenT0r$@2024_2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - medisync-network

networks:
  medisync-network:
    name: medisync-network
    driver: bridge

volumes:
  postgres_data: